[package]
name = "gm48-scraper"
version = "0.3.2"
authors = ["BioTomateDE <biotomatede@proton.me>"]
edition = "2024"
description = "CLI for scraping GameMaker data files from the GM48 Game Jam"
readme = "./README.md"
repository = "https://codeberg.org/BioTomateDE/GM48Scraper"
license = "GPL-3.0-or-later"
keywords = ["gamemaker", "scraping", "cli"]
categories = ["command-line-utilities"]

[badges]
maintenance.status = "passively-maintained"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
colored-print = "0.1"

# I really don't like this dependency because of its horrid
# build script, but it works flawlessly for SFX archives.
# Feel free to replace this dependency when there is Rust-native solution.
compress-tools = "0.15"

futures = "0.3"
humansize = "2.1"
reqwest = "0.13"
sanitise-file-name = "1.0"
scraper = "0.26"
tokio = { version = "1.50", features = ["macros", "rt-multi-thread"] }
urlencoding = "2.1"

